/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        serif: ['"Cormorant Garamond"', "Georgia", "serif"],
        sans: ['"Inter"', "system-ui", "sans-serif"],
      },
      colors: {
        ink: {
          50: "#f6f5f1", 100: "#e9e6dd", 200: "#d3ccbb", 300: "#b5ab92",
          400: "#948766", 500: "#7a6d4f", 600: "#5f543d", 700: "#473f2f",
          800: "#2e2920", 900: "#1a1712", 950: "#0d0b08",
        },
        accent: {
          50: "#fff8ed", 100: "#ffefd4", 200: "#ffdba8", 300: "#ffc070",
          400: "#ff9d37", 500: "#f97c0f", 600: "#ea5d06", 700: "#c24407",
          800: "#9a370e", 900: "#7c2f0f",
        },
      },
      keyframes: {
        "fade-in": { "0%": { opacity: "0" }, "100%": { opacity: "1" } },
        "fade-up": { "0%": { opacity: "0", transform: "translateY(24px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "fade-down": { "0%": { opacity: "0", transform: "translateY(-24px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "blink-cursor": { "0%, 100%": { opacity: "1" }, "50%": { opacity: "0" } },
        "float-slow": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-12px)" } },
        "float-up": { "0%": { transform: "translateY(0) scale(1)", opacity: "0.6" }, "100%": { transform: "translateY(-100vh) scale(0.3)", opacity: "0" } },
        "gradient-pan": { "0%, 100%": { backgroundPosition: "0% 50%" }, "50%": { backgroundPosition: "100% 50%" } },
        "drift": { "0%": { transform: "translateX(0) translateY(0)" }, "33%": { transform: "translateX(30px) translateY(-20px)" }, "66%": { transform: "translateX(-20px) translateY(15px)" }, "100%": { transform: "translateX(0) translateY(0)" } },
        "shimmer": { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
        "pulse-ring": { "0%": { transform: "scale(0.8)", opacity: "0.8" }, "100%": { transform: "scale(2.4)", opacity: "0" } },
        "aurora": { "0%, 100%": { transform: "translate(0,0) rotate(0deg)" }, "50%": { transform: "translate(40px,-30px) rotate(180deg)" } },
        "scale-in": { "0%": { transform: "scale(0.9)", opacity: "0" }, "100%": { transform: "scale(1)", opacity: "1" } },
        "slide-in-right": { "0%": { transform: "translateX(100%)" }, "100%": { transform: "translateX(0)" } },
        "leaf-fall": { "0%": { transform: "translateY(-10vh) translateX(0) rotate(0deg)", opacity: "0.8" }, "100%": { transform: "translateY(110vh) translateX(50px) rotate(360deg)", opacity: "0" } },
        "snow-fall": { "0%": { transform: "translateY(-10vh) translateX(0)", opacity: "0.8" }, "100%": { transform: "translateY(110vh) translateX(20px)", opacity: "0" } },
        "blossom-float": { "0%": { transform: "translateY(-10vh) translateX(0) rotate(0deg)", opacity: "0.6" }, "100%": { transform: "translateY(110vh) translateX(80px) rotate(180deg)", opacity: "0" } },
        "ink-spread": { "0%": { opacity: "0", filter: "blur(8px)" }, "50%": { opacity: "0.8", filter: "blur(2px)" }, "100%": { opacity: "1", filter: "blur(0)" } },
        "page-turn": { "0%": { transform: "rotateY(0deg)" }, "100%": { transform: "rotateY(-180deg)" } },
        "ticker-scroll": { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
      },
      animation: {
        "fade-in": "fade-in 1.2s ease-out forwards",
        "fade-up": "fade-up 0.9s ease-out forwards",
        "fade-down": "fade-down 0.9s ease-out forwards",
        "blink-cursor": "blink-cursor 1s step-end infinite",
        "float-slow": "float-slow 6s ease-in-out infinite",
        "float-up": "float-up 18s linear infinite",
        "gradient-pan": "gradient-pan 12s ease infinite",
        "drift": "drift 20s ease-in-out infinite",
        "shimmer": "shimmer 3s linear infinite",
        "pulse-ring": "pulse-ring 3s ease-out infinite",
        "aurora": "aurora 30s ease-in-out infinite",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "slide-in-right": "slide-in-right 0.3s ease-out forwards",
        "leaf-fall": "leaf-fall 12s linear infinite",
        "snow-fall": "snow-fall 10s linear infinite",
        "blossom-float": "blossom-float 14s linear infinite",
        "ink-spread": "ink-spread 2s ease-out forwards",
        "page-turn": "page-turn 0.6s ease-in-out forwards",
        "ticker-scroll": "ticker-scroll 30s linear infinite",
      },
    },
  },
  plugins: [],
};
